### ISSUE TITLE
Header Scanner crashes by wrong encoded headers

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/HSHS-DOMXSS-Scanner#24]
Please check this:

```
$ curl -X HEAD -v https://sekund.eu/ 2>&1 | grep options | xd
00000: 3c 20 78 2d  66 72 61 6d - 65 2d 6f 70  74 69 6f 6e [< x-frame-option]
00010: 73 3a 20 53  41 4d 45 4f - 52 49 47 49  4e 2c 20 53 [s: SAMEORIGIN, S]
00020: 41 4d 45 4f  52 49 47 49 - 4e 0d 0a 3c  20 78 2d 66 [AMEORIGIN..< x-f]
00030: 72 61 6d 65  2d 6f 70 74 - 69 6f 6e 73  3a 20 53 41 [rame-options: SA]
00040: 4d 45 4f 52  49 47 49 4e - 2c 20 53 41  4d 45 4f 52 [MEORIGIN, SAMEOR]
00050: 49 47 49 4e  0d 0a 3c 20 - 78 2d 63 6f  6e 74 65 6e [IGIN..< x-conten]
00060: 74 2d 74 79  70 65 2d 6f - 70 74 69 6f  6e 73 3a 20 [t-type-options: ]
00070: 84 6e 6f 73  6e 69 66 66 - 93 0d 0a ..  .. .. .. .. [.nosniff...     ]
```

There are more header lines containing 0x84 0x93 instead of single quets (which would be wrong anyway I guess).

The issue here is: HEADER scanner seems to crash as we get a timeout for it.

Will check now the logs.

**Comment by Skeeve** [comment]
There is absolutely nothing in the laravel.log for the domain. Even when starting a new scan. Nothing appears in the logs.

**Comment by Skeeve** [comment]
I reproduced the error on my private de domain. Feel free to check there. Tell me when done so I can revert those changes.

**Comment by Skeeve** [comment]
Found it…

```
[2018-06-29 09:38:26] production.INFO: InvalidArgumentException: json_encode error: Malformed UTF-8 characters, possibly incorrectly encoded in /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/guzzlehttp/guzzle/src/functions.php:327
Stack trace:
#0 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/guzzlehttp/guzzle/src/Client.php(323): GuzzleHttp\json_encode(Array)
#1 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/guzzlehttp/guzzle/src/Client.php(273): GuzzleHttp\Client->applyOptions(Object(GuzzleHttp\Psr7\Request), Array)
#2 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#3 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Client->requestAsync('post', Object(GuzzleHttp\Psr7\Uri), Array)
#4 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\Client->request('post', 'https://ca.stag...', Array)
#5 /var/www/sites.d/staging/live-hshs/releases/20180625135616/app/Http/Controllers/ApiController.php(60): GuzzleHttp\Client->__call('post', Array)
#6 /var/www/sites.d/staging/live-hshs/releases/20180625135616/app/Http/Controllers/ApiController.php(21): App\Http\Controllers\ApiController->notifyCallbacks(Array, Object(App\HeaderCheck))
#7 [internal function]: App\Http\Controllers\ApiController->headerReport(Object(Illuminate\Http\Request))
#8 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#9 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('headerReport', Array)
#10 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\ApiController), 'headerReport')
#11 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#12 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#13 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), 60, '1')
#19 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#23 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#24 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#25 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#26 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/sites.d/staging/live-hshs/releases/20180625135616/app/Http/Middleware/SetLocaleMiddleware.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\Http\Middleware\SetLocaleMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#41 /var/www/sites.d/staging/live-hshs/releases/20180625135616/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#42 /var/www/sites.d/staging/live-hshs/releases/20180625135616/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#43 {main}
```

**Comment by Skeeve** [comment]
So it's mainly that the scanner receives a non-utf8 string and upon encoding it, php fails.

I would assume that such a wrong string should be considered bad and that it should be reported to the customer somehow.
